### PR TITLE
Responsive styles

### PR DESCRIPTION
**Pull request by mckernanin**
I went through and added some nice looking responsive styles. 
scout-realtime-ipad-landscape
scout-realtime-ipad-portrait
scout-realtime-iphone

### CODE REVIEW

**Comment by itsderek23** [comment]
Thanks @mckernanlive! We'll check it this week.

**Comment by mckernanin** [comment]
Any update?

**Comment by andre** [comment]
Sorry, not yet, Kevin. We've been heads down working on new Scout features.

**Comment by mckernanin** [comment]
No worries, just wanted to check!

**Comment by SebastianSzturo** [comment]
Great work @mckernanin!
Can we see this :ship: anytime soon?

**Comment by mckernanin** [comment]
I don't have it up anywhere anymore, I just added styles, I didn't change any existing, so it should be able to be added to the end of the existing stylesheet.

**Comment by paviro** [comment]
Any chance this gets added to the official release?

**Comment by mckernanin** [comment]
Is this project dead?

**Pull request closed without merging**
