### PR TITLE
Change language to be non-gender-specific

### PR DESCRIPTION
**Pull request by gdiggs**
Everyone should be included in a tool this awesome

### CODE REVIEW

**Comment by yahelc** [comment]
HI @halfdan, thanks for the support. It's worth noting that, at least in American idiomatic English, the phrase "for the modern man" is very gender specific in how its used. https://www.google.com/search?q=%22for+the+modern+man%22 

Without the `the`, I guess it could be read as contrasting modern humans to primitive humans, but with the `"the"`, it's `"the man"`, which isn't really ever used in English for referring to humans as a species in a non-gender specific way.

**Comment by mejackreed** [comment]
+1

**Comment by andre** [comment]
Didn't mean to exclude anyone! merging.

**Comment by yahelc** [comment]
Thanks @andre!

**Pull request merged**
