### PR TITLE
Include server hostname in <title>

### PR DESCRIPTION
**Pull request by qrohlf**
This is helpful for when scout_realtime is running on multiple servers and I want to have each one open in a browser tab.

### CODE REVIEW

**Comment by jippi** [comment]
:+1:

**Comment by Oxicode** [comment]
:+1:

**Comment by qrohlf** [comment]
@itsderek23, @andre - anything I missed in order to get this merged in?

**Comment by itsderek23** [comment]
Sorry @qrohlf  - merged!

**Comment by itsderek23** [comment]
I moved the hostname before "Scout Realtime" (makes the hostname visible with many tabs open).

**Comment by qrohlf** [comment]
good call - thanks!

**Pull request merged**
